podTemplate( //idleMinutes: 30, 
    yaml: '''
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  volumes:
    - name: docker-insecure-registries
      configMap:
        name: harbor-allow-insecure-registries
        items:
          - key: daemon.json
            path: daemon.json
    - name: cache
      hostPath:
        path: /tmp
        type: Directory
    - name: m2
      persistentVolumeClaim:
        claimName: jenkins-pvc1
  serviceAccountName: jenkins-sa
  containers:
  - name: docker
    image: docker:19.03.1-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    volumeMounts:
    - name: cache
      mountPath: /var/lib/docker
    - name: docker-insecure-registries
      mountPath: /etc/docker/daemon.json
      subPath: daemon.json
  - name: maven
    image: maven:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: "/root/.m2"
      name: m2
  - name: kpack
    image: kpack/kp
    command:
    - cat
    tty: true
''') {
    node(POD_LABEL) {
        
        // stage("GIT") {
        //   git credentialsId: 'pvt-repo-cred', branch: 'main', url: 'https://github.com/alinahid477/vmw-calculator-addservice.git'
        // }
        
        // stage("MAVEN") {
        //   container('maven') {
        //       sh """
        //           mvn package -DskipTests
        //       """
        //   }
        // }
        


        stage("TBS") {
          container('kpack') {
            withKubeConfig([credentialsId: 'jenkins-robot',
                        serverUrl: 'https://i77kmduc86zbn3lvt7hkwiwonpbp-k8s-93180135.ap-southeast-2.elb.amazonaws.com:443',
                        clusterName: 'testpipeline',
                        namespace: 'build-service'
                        ]) {
              sh 'kubectl config view'
              sh 'kubectl get pods'
              sh """
                kp image save vmw-calculator-addservice-build --git https://github.com/alinahid477/vmw-calculator-addservice.git --git-revision main --tag anahidcalcacr.azurecr.io/calcaddservice --builder default-builder --wait
              """
            }
          }
          
        }
        
        stage("K8S") {
          withKubeConfig([credentialsId: 'jenkins-robot',
                      serverUrl: 'https://i77kmduc86zbn3lvt7hkwiwonpbp-k8s-93180135.ap-southeast-2.elb.amazonaws.com:443',
                      clusterName: 'testpipeline',
                      namespace: 'default'
                      ]) {
            sh 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
            // sh 'cat $(ls -la | grep config | awk '{print $9}')'
            sh 'chmod 777 ./kubectl'
            sh './kubectl apply -f kubernetes/deployment.yaml'
            // sh './kubectl patch deployment addservice-deploy -p \"{\\"spec\\": {\\"template\\": {\\"metadata\\": { \\"labels\\": {  \\"redeploy\\": \\"$(date +%s)\\"}}}}}\" -n calculator'
          }
        }
                  
        
    }
}
